import { HorizontalBox, Palette } from "std-widgets.slint";
import { CPUPanel } from "cpu_panel.slint";

component PanelButton inherits Rectangle {
    height: 40px;
    border-width: 2px;
    border-radius: 4px;
    background: Palette.border;
}
export component MainWindow inherits Window {
    preferred-width: 1000px;
    preferred-height: 600px;

    HorizontalLayout {
        Rectangle {
            min-width: 150px;
            max-width: 250px;
            height: 100%;
            background: Palette.background;
            border-width: 2px;
            border-color: Palette.border;
            VerticalLayout {
                padding: 8px;
                spacing: 4px;
                PanelButton {}
                PanelButton {}
                PanelButton {}
                PanelButton {}
                PanelButton {}
                PanelButton {}
                Rectangle {}
            }
           
        }
        VerticalLayout {
            Rectangle{
                min-width: 300px;
                height: 75px;
                background: Palette.background;
                border-width: 2px;
                border-color: Palette.border;
            }
            Rectangle{
                min-width: 300px;
                background: Palette.background;
                border-width: 2px;
                border-color: Palette.border;
                CPUPanel {}
            }
        }
    }
}